# These are supported funding model platforms

github: [reblox01]
patreon: aroscki
paypal: SohailKoutari
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: arosck1
custom:
